In [1]:
import numpy as np
import pandas as pd

In [2]:
# read date from csv file
data = pd.read_csv('fatigue_data.csv', index_col='Sl. No.')

# set X as columns C, Ni, Cr and Mo (No.16-19)
Xf = data.drop(data.columns[16:20], axis=1) 
# set y as 'Fatigue' column (No.17)
yf = data['Fatigue']

Xf.shape, yf.shape

((437, 16), (437,))

In [3]:
# read date from xlsx file
data = pd.read_excel('kappa.xlsx')

Xk = data.drop(data.columns[0:3], axis=1).drop(data.columns[-1], axis=1)
yk = data[data.columns[-1]]

Xk.shape, yk.shape

((320, 36), (320,))

In [5]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler

In [22]:
# Variance Threshold
thresholder = VarianceThreshold(threshold=100)
features_high_variance = thresholder.fit_transform(Xf)

features_high_variance

array([[885.,  30.,   0., ...,  30.,  30.,   0.],
       [885.,  30.,   0., ...,  30.,  30.,   0.],
       [885.,  30.,   0., ...,  30.,  30.,   0.],
       ...,
       [930.,  30.,   0., ...,  60., 200., 120.],
       [930.,  30.,   0., ...,  60., 200., 120.],
       [930.,  30.,   0., ...,  60., 200., 120.]])

In [23]:
thresholder.fit(Xf).variances_

array([6.85500526e+02, 7.82410122e+04, 1.05105017e+02, 6.13474229e+01,
       7.91977756e+04, 1.60730141e+04, 7.11945768e+04, 2.45928321e+02,
       3.76245359e+02, 2.68678309e+04, 4.60233860e+02, 6.50114102e+01,
       9.26471103e-03, 7.25902728e-01, 1.69165923e-01, 7.74801250e-03])

In [28]:
# Feature scaling
scaler = StandardScaler()
Xf_std = scaler.fit_transform(Xf)

selector = VarianceThreshold()

# output 1 means that feature noramlization is scuccessful
selector.fit(Xf_std).variances_

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])